server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /**     # 静态资源匹配模式
  web:
    resources:
      static-locations:          # 静态资源位置
        - classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456 #修改成自己数据库的密码
  mail:
    host: smtp.qq.com          # QQ邮箱SMTP服务器
    port: 587                  # 端口（587或465）
    username: 3380377624@qq.com
    password: vzaqmuphwanmdbhb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.movie.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: bW92aWVfc3lzdGVtX3NlY3JldF9rZXlfMjAyNg=
  expiration: 86400000

logging:
  level:
    com.movie: DEBUG